export enum DrawEventType {
  // Handling persistence
  DRAW_CREATED = 'DRAW_CREATED',
  DRAW_DELETED = 'DRAW_DELETED',

  // Handling stakeholders updates
  STAKEHOLDER_SUBSCRIBED = 'STAKEHOLDER_SUBSCRIBED',
  STAKEHOLDER_UNSUBSCRIBED = 'STAKEHOLDER_UNSUBSCRIBED',

  // Handling commits and reveals
  COMMIT_SENT = 'COMMIT_SENT',
  REVEAL_SENT = 'REVEAL_SENT',
  ALL_COMMITS_RECEIVED = 'ALL_COMMITS_RECEIVED',
  ALL_REVEALS_RECEIVED = 'ALL_REVEALS_RECEIVED',

  // Handling draw status changes
  STATUS_CHANGED = 'STATUS_CHANGED',

  // Handling format exceptions
  WRONG_COMMIT_FORMAT = 'INVALID_COMMIT_FORMAT',
  WRONG_REVEAL_FORMAT = 'INVALID_REVEAL_FORMAT',

  // Handling inconsistencies and cheats
  INVALID_REVEAL_MASK = 'INVALID_REVEAL_MASK',

  // Handling authencation
  UNAUTHORIZED_COMMIT_SIGNATURE = 'UNAUTHORIZED_COMMIT_SIGNATURE',
  UNAUTHORIZED_REVEAL_SIGNATURE = 'UNAUTHORIZED_REVEAL_SIGNATURE',
}
